<a href="https://colab.research.google.com/github/yeseniaandrade/yeseniaandrade-IS_4487_Tokyo/blob/main/Yesenia_Andrade_copy_of_day2_lab_megatelco_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Day 2 Lab, IS 4487

Outline

- Loading installed packages
- Inspect data
- Clean data
- Summarize data

# Notebook Instructions

Again, remember to save a copy of the notebook in Drive so that you can save your changes.

When you are done revising this notebook save your changes to GitHub and upload the URL for the file to Canvas for the assignment.

# Clean and Prepare the MegaTelCo Data

##Load Libraries

Remember, we will be using:
- Pandas
- Scikitlearn
- Matplotlib

In [1]:
import pandas as pd
import matplotlib as mpl
import sklearn as sl

## Load the Data

In this case we will load  the MegaTelCo data directly from the URL in GitHub.

In [15]:
mtc = pd.read_csv("https://raw.githubusercontent.com/jefftwebb/is_4487_base/dd870389117d5b24eee7417d5378d80496555130/Labs/DataSets/megatelco_leave_survey.csv")

Examine the data quickly for mistakes and to get a sense of the variables:

In [16]:
#look at the top rows
mtc.head(10)

,college,income,overage,leftover,house,handset_price,over_15mins_calls_per_month,average_call_duration,reported_satisfaction,reported_usage_level,considering_change_of_plan,leave,id
0,one,23859,70,0,519105,154,5.0,8,low,low,yes,LEAVE,8183
1,zero,72466,67,16,271182,262,5.0,5,low,low,yes,LEAVE,12501
2,zero,30883,60,0,647281,211,3.0,8,low,low,yes,STAY,7425
3,one,44512,0,22,754958,232,0.0,5,low,low,no,LEAVE,13488
4,zero,70535,0,0,653421,310,0.0,14,low,low,yes,STAY,11389
5,zero,143987,0,56,896544,778,5.0,1,low,high,yes,STAY,14674
6,one,96668,79,24,259329,365,5.0,6,low,avg,yes,LEAVE,19100
7,one,50083,0,0,160335,266,5.0,10,low,high,yes,STAY,18170
8,one,104392,0,0,247836,778,1.0,8,high,low,no,LEAVE,3201
9,one,37852,0,74,264893,857,0.0,2,low,low,yes,LEAVE,12612

In [17]:
#look at last rows
mtc.tail(10)

,college,income,overage,leftover,house,handset_price,over_15mins_calls_per_month,average_call_duration,reported_satisfaction,reported_usage_level,considering_change_of_plan,leave,id
4990,one,158179,226,21,269368,478,18.0,5,avg,high,yes,LEAVE,18481
4991,one,75711,47,0,519512,326,4.0,12,high,high,yes,STAY,9790
4992,one,34039,59,0,541872,165,3.0,10,low,high,yes,STAY,19985
4993,zero,88713,0,70,587559,319,0.0,2,low,low,yes,LEAVE,17220
4994,zero,123820,0,71,608639,888,1.0,2,low,high,yes,STAY,10396
4995,zero,93699,26,56,385632,384,5.0,1,high,low,yes,LEAVE,19270
4996,zero,25806,67,87,691020,142,4.0,2,high,low,no,STAY,14549
4997,one,97033,138,28,710559,311,10.0,2,low,high,yes,STAY,9972
4998,zero,91558,229,15,853464,379,27.0,4,high,low,no,STAY,12685
4999,one,115943,200,42,173038,459,24.0,2,high,high,yes,LEAVE,13561

In [18]:
#get a summary of the dataset
mtc.describe()

,income,overage,leftover,house,handset_price,over_15mins_calls_per_month,average_call_duration,id
count,5000.000000,5000.000000,5000.000000,5000.000000,5.000000e+03,4997.000000,5000.000000,5000.000000
mean,79912.948400,85.119200,24.243600,493656.326600,7.876236e+02,7.744647,5.958800,10036.639400
std,41703.042384,85.655622,26.847496,254287.193865,2.828291e+04,8.806070,4.390417,5813.620304
min,-28811.000000,0.000000,0.000000,-796132.000000,1.300000e+02,0.000000,1.000000,2.000000
25%,41592.500000,0.000000,0.000000,260586.500000,2.190000e+02,1.000000,2.000000,4950.500000
50%,75041.500000,59.000000,15.000000,451865.500000,3.220000e+02,4.000000,5.000000,10126.000000
75%,115475.000000,177.000000,42.000000,701608.750000,5.280000e+02,14.000000,9.000000,15085.250000
max,159938.000000,335.000000,89.000000,1000000.000000,2.000234e+06,29.000000,15.000000,20000.000000

In [19]:
#look at the datatypes
mtc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   college                      5000 non-null   object
 1   income                       5000 non-null   int64
 2   overage                      5000 non-null   int64
 3   leftover                     5000 non-null   int64
 4   house                        5000 non-null   int64
 5   handset_price                5000 non-null   int64
 6   over_15mins_calls_per_month  4997 non-null   float64
 7   average_call_duration        5000 non-null   int64
 8   reported_satisfaction        5000 non-null   object
 9   reported_usage_level         5000 non-null   object
 10  considering_change_of_plan   5000 non-null   object
 11  leave                        5000 non-null   object
 12  id                           5000 non-null   int64
dtypes: float64(1), int64(7), object(5)
memory usage: 507.9+ KB


Did you notice anything unusual about the amounts for `house`?  And what about `handset_price` and `income`? The data needs to be cleaned by selecting and filtering the data.

## Data Selection and Filtering in Pandas

Data selection and filtering are essential techniques for working with Pandas DataFrames. They allow you to extract specific subsets of data based on certain conditions.

## Selecting Specific Columns

Square bracket subsetting, or indexing, is a way to access specific rows and columns of a DataFrame. When you use square brackets, `[]`, with a DataFrame  you can pass in:

- A single column name to select a single column (returns a Series)
- A list of column names to select multiple columns (returns a DataFrame)
- A boolean mask to select rows based on a condition
- A slice to select a range of rows

For example, `mtc['college']` selects the `college` column as a Series, while `mtc[['college', 'income']]` selects the `college` and `income` columns as a DataFrame.

In [7]:
mtc['college']

0        one
1       zero
2       zero
3        one
4       zero
        ...
4995    zero
4996    zero
4997     one
4998    zero
4999     one
Name: college, Length: 5000, dtype: object

In [8]:
mtc[['college', 'income']]

     college  income
0        one   23859
1       zero   72466
2       zero   30883
3        one   44512
4       zero   70535
...      ...     ...
4995    zero   93699
4996    zero   25806
4997     one   97033
4998    zero   91558
4999     one  115943

[5000 rows x 2 columns]

## Your Turn: Selecting Columns

1. Select the `overage` column from `mtc`.
2. Select the `overage` *and* `leftover` columns from `mtc`.

In [21]:
# Your code goes here
mtc['overage']

0        70
1        67
2        60
3         0
4         0
       ...
4995     26
4996     67
4997    138
4998    229
4999    200
Name: overage, Length: 5000, dtype: int64

In [22]:
# Your code goes here
mtc[['overage', 'leftover']]

      overage  leftover
0          70         0
1          67        16
2          60         0
3           0        22
4           0         0
...       ...       ...
4995       26        56
4996       67        87
4997      138        28
4998      229        15
4999      200        42

[5000 rows x 2 columns]

## Filtering Rows with Boolean Masks

Boolean masking is a powerful technique for filtering rows based on certain conditions. You create a boolean mask by applying a logical condition to a DataFrame, which returns  True/False values. You can then use this mask to select the rows where the condition is True.

In [11]:
# Here is the mask:
mtc["handset_price"] > 1000

0       False
1       False
2       False
3       False
4       False
        ...
4995    False
4996    False
4997    False
4998    False
4999    False
Name: handset_price, Length: 5000, dtype: bool

In [12]:
# Now, filter with the mask:
mtc[mtc["handset_price"] > 1000]

,college,income,overage,leftover,house,handset_price,over_15mins_calls_per_month,average_call_duration,reported_satisfaction,reported_usage_level,considering_change_of_plan,leave,id
299,zero,83525,246,53,308636,2000234,27.0,1,low,high,no,LEAVE,14137

Notice that the number of rows has gone from 5000 down to 1.  Of course, for cleaning we would want to *exclude* this row.

## Your Turn:  Data Cleaning

1.  Use a boolean mask to filter out rows with mistakes using three logical conditions:
  - remove the outlier in `handset_price`
  - remove rows with negative values of `income` and `house`
2. Save the cleaned data in a new DataFrame, `mtc_clean`.
3. Summarize this new DataFrame to verify that your changes worked.

In [28]:
# Your code goes here
mask = mtc_clean["handset_price"] < 1000

In [27]:
mask = (mtc["handset_price"] < 1000) & (mtc["income"] > 0) & (mtc["house"] > 0)
mtc_clean = mtc[mask]
mtc_clean.describe()

,income,overage,leftover,house,handset_price,over_15mins_calls_per_month,average_call_duration,id
count,4997.000000,4997.000000,4997.000000,4997.000000,4997.000000,4994.000000,4997.000000,4997.000000
mean,79918.829498,85.116270,24.247549,494019.823294,387.558935,7.739287,5.957174,10034.365619
std,41673.392025,85.638266,26.848091,253648.357473,213.614256,8.802897,4.388938,5814.189195
min,20028.000000,0.000000,0.000000,150305.000000,130.000000,0.000000,1.000000,2.000000
25%,41593.000000,0.000000,0.000000,260729.000000,219.000000,1.000000,2.000000,4949.000000
50%,75026.000000,59.000000,15.000000,452277.000000,322.000000,4.000000,5.000000,10125.000000
75%,115464.000000,177.000000,42.000000,701614.000000,528.000000,14.000000,9.000000,15084.000000
max,159938.000000,335.000000,89.000000,1000000.000000,899.000000,29.000000,15.000000,20000.000000

In [26]:
# Your code goes here
mask = (mtc["handset_price"] < 1000) & (mtc["income"] > 0) & (mtc["house"] > 0)
mtc_clean = mtc[mask]
mtc_clean.describe()

,income,overage,leftover,house,handset_price,over_15mins_calls_per_month,average_call_duration,id
count,4997.000000,4997.000000,4997.000000,4997.000000,4997.000000,4994.000000,4997.000000,4997.000000
mean,79918.829498,85.116270,24.247549,494019.823294,387.558935,7.739287,5.957174,10034.365619
std,41673.392025,85.638266,26.848091,253648.357473,213.614256,8.802897,4.388938,5814.189195
min,20028.000000,0.000000,0.000000,150305.000000,130.000000,0.000000,1.000000,2.000000
25%,41593.000000,0.000000,0.000000,260729.000000,219.000000,1.000000,2.000000,4949.000000
50%,75026.000000,59.000000,15.000000,452277.000000,322.000000,4.000000,5.000000,10125.000000
75%,115464.000000,177.000000,42.000000,701614.000000,528.000000,14.000000,9.000000,15084.000000
max,159938.000000,335.000000,89.000000,1000000.000000,899.000000,29.000000,15.000000,20000.000000

# Summarize the Data

 Previously we used a built-in summary function, `info()`, to summarize the numeric columns in a dataset. However, we can write code to do more complicated data summaries.

 Question:  What is average value of `house` at the two levels of `leave`?  (We call this a conditional mean because it is *conditional* on the value of `leave`.)

In [ ]:
mtc_clean[['house','leave']].groupby('leave').mean().round(2)

Details:

- `[[...]]`: Used to select specific columns (`house` and `leave`) from `mtc_clean`.
- `groupby()`:  Groups the data by the `leave` column, creating separate groups for each unique value in `leave`.
- `mean()`: Calculates the average of the `house` column for each group created by `groupby()`.
- `round(2)`: Rounds the resulting mean values to 2 decimal places.


 Conclusion?  Stayers have substantially more expensive homes.

## Your Turn: Calculate Additional Stats

Use `mtc_clean` to:

1. Calculate means conditional on leave for `income` and `overage`.
2. Calculate *median* income for leavers and stayers. (Hint:  use the Gemini AI tool to figure out what function will calculate a median.)
3. Calculate the 25th and 75th percentiles for `income`.  (Again use Gemini for help.)

In [36]:
# Your code goes here
mtc_clean[['income','overage', 'leave']].groupby('leave').mean().round(2)

         income  overage
leave
LEAVE  84648.06   104.70
STAY   75292.57    65.95

In [31]:
# Your code goes here
mtc_clean[mtc_clean['leave'] == 1]['income'].median()
mtc_clean[mtc_clean['leave'] == 0]['income'].median()

nan

In [33]:
# Your code goes here
mtc_clean['income'].quantile(0.25)

41593.0

In [34]:
# Your code goes here
mtc_clean['income'].quantile(0.75)

115464.0

# Functions

- `pd.read_csv()`:  Reads a CSV file into a pandas DataFrame.
- `.head()`: Returns the first n rows of a DataFrame or Series (default is 5).
- `.tail()`: Returns the last n rows of a DataFrame or Series (default is 5).
- `.describe()`: Generates descriptive statistics of a DataFrame or Series.
- `.info()`: Prints a concise summary of a DataFrame, including column names, non-null counts, and data types.
- `[]` and `[[ ]]` (indexing):  Used to select specific columns or rows from a DataFrame.
- `.groupby()`: Groups DataFrame using a mapper or by a Series of columns.
- `.mean()`:  Returns the mean of the values for the requested axis.
- `.round()`:  Rounds a number or DataFrame to a specified number of decimal places.